// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using octoco_backend_test.Models;

#nullable disable

namespace octoco_backend_test.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230222132539_SetupDatabase")]
    partial class SetupDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("octoco_backend_test.Survivor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Inventory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isInfected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Survivors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            Gender = 0,
                            Inventory = "{\"Water Bottles\":5,\"Ammo\":49,\"Guns\":1}",
                            Latitude = -32.241844,
                            Longitude = 22.299499999999998,
                            Name = "John",
                            isInfected = false
                        },
                        new
                        {
                            Id = 2,
                            Age = 33,
                            Gender = 1,
                            Inventory = "{\"Food\":10,\"Medicine\":2,\"Ammo\":15}",
                            Latitude = 40.712775999999998,
                            Longitude = -74.005973999999995,
                            Name = "Mary",
                            isInfected = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 45,
                            Gender = 0,
                            Inventory = "{\"Water Bottles\":2,\"Gasoline\":5}",
                            Latitude = 51.507351,
                            Longitude = -0.12775800000000001,
                            Name = "Tom",
                            isInfected = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
